### ISSUE TITLE
As a student, I want to be able to join the mining network so that I can earn rewards by mining blocks

### ISSUE THREAD

**Issue by abhisachdev17** [ZackHolmberg/COMP4350-Project#10]
**Acceptance Criteria:**

_Scenario:_ Student joins the mining network.

“Given that I am on the home page
And the mining button is set to off
When I click toggle the mining button on
Then I begin participating in the mining session to earn rewards”

**Related Dev Tasks:**

- [x] #22 Initialize mining service.
- [x]  #11 Mining on user devices.
- [x]  #12 Miner service to facilitate mining operations.
- [x]  #56 Implement mining component.
- [x]  #9 Transactions are picked from the queue and added to chain.
