### ISSUE TITLE
As a student, I want to manage my account so that I can update my account information

### ISSUE THREAD

**Issue by ZackHolmberg** [ZackHolmberg/COMP4350-Project#55]
**Acceptance Criteria:**

_Scenario:_ Student updates their account information.

“Given that I am on the home page
When I select Account in nav bar 
And I click Edit button
And I change at least one of the fields 
And I click the Save button
Then the app saves and displays the updated information”

**Related Dev Tasks:**

- [x] #54 Implement view account component.
- [x] #63 Implement edit account functionality.
- [x] #27 Create navbar component.
