### ISSUE TITLE
Manage Account

### ISSUE THREAD

**Issue by madisonfines** [ZackHolmberg/COMP4350-Project#60]
**Description:**

Students will be able to create an account, login into the app with their credentials, and manage their account information.

**Related User Stories:**

- [x] #62 As a student, I want to create an account so that I can use the BisonCoin app.
- [x] #55 As a student, I want to manage my account so that I can update my account information.
- [x] #125 As a student, I want the ability to login so that I can access my account.
- [x] #126 As a student, I want the ability to log out so that I can leave my account.
