### ISSUE TITLE
As a student, I want to create an account so that I can use the BisonCoin app

### ISSUE THREAD

**Issue by madisonfines** [ZackHolmberg/COMP4350-Project#62]
**Acceptance Criteria:**

_Scenario:_ Student creates a new account.

“Given that I am on the login page
And I click Create New Account link
When I fill in the required authentication fields
And I click the Create Account button
Then the app creates a new account with my credentials
And logs me in”

**Related Dev Tasks:**

- [x] #44 Initialize user service.
- [x] #43 Create MongoDB service.
- [x] #53 Implement create account page.
