### ISSUE TITLE
As a student, I want to view my wallet so that I can see how much BisonCoin I have

### ISSUE THREAD

**Issue by madisonfines** [ZackHolmberg/COMP4350-Project#64]
**Acceptance Criteria:**

_Scenario:_ Student views the amount of BisonCoin they have in their wallet.

“Given that I am on the home page of the app 
When I view wallet
Then I am able to view my current balance”

**Related Dev Tasks:** 

- [x] #48 Initialize wallet service.
- [x] #5 Implement wallet-api endpoints.
- [x] #4 Implement wallet component.
