### ISSUE TITLE
As a student, I want to view my transaction history so that I can view details about my previous transactions

### ISSUE THREAD

**Issue by madisonfines** [ZackHolmberg/COMP4350-Project#65]
**Acceptance Criteria:**

_Scenario:_ Student views their transaction history.

“Given that I am on the home page
When I click transaction history list button
Then I am able to view my past transactions”

**Related Dev Tasks:**

- [x] #29 Create transaction history component.
- [x] #99 Implement transaction history retrieval.
- [x] #101 Client checks for new transactions.

**Comment by abhisachdev17** [comment]
can we close this too?
