### ISSUE TITLE
As a student, I want to be able to transfer BisonCoin so that I can send currency to other users

### ISSUE THREAD

**Issue by abhisachdev17** [ZackHolmberg/COMP4350-Project#7]
**Acceptance Criteria:**

_Scenario:_ Student transfers BisonCoin to a recipient.

“Given that I am on the home page
When I click new transaction button
And I input amount and recipient
And I click send button
Then the proper BisonCoin amount is transferred to my intended recipient
And my wallet amount decreases”

**Related Dev Tasks:**

- [x] #18 Initialize transaction service.
- [x] #30 Create new transaction component.
- [x] #8 Accept transactions from the frontend and pass it to mining service.
